### PR TITLE
Include: Stock Market

### PR DESCRIPTION
**Pull request by jacobkossman**
Added the preliminary functionality of a stock market include since I see you didn't start one. Haven't gotten to buy / sell, you may have more expertise in regards to these in terms of needing referrers etc.

### CODE REVIEW

**Comment by w35l3y** [comment]
I will check it as soon as I get home. Thanks @jacobkossman

**Comment by jacobkossman** [comment]
@w35l3y how do i not add my new commits to this pull request lol.

**Comment by w35l3y** [comment]
This is a very good question. Did you pull request again?
Don't worry. I will check the whole code.

**Comment by jacobkossman** [comment]
nope. no new pull requests.

i've been updating the food club include with a bunch of new functions and editing the training school one because you couldn't choose a pet (as it would default to active). feel free to take or not take whatever you choose!

**Comment by w35l3y** [comment]
It will consider the active pet unless you specify as 2nd parameter :) 
`var TrainingSchool = function (page, pet) {`

**Comment by jacobkossman** [comment]
yeah but that means you have to make an instance for each pet, no? is that a "better" option?

**Comment by w35l3y** [comment]
Yes, that's right.
I think it's better to create a instance for each pet then passing the same parameter every time. What do you think? You have very good questions.

**Comment by jacobkossman** [comment]
i totally didn't think about making multiple instances. i like the idea of using the parameter because you can then more easily loop to finish / start all courses regardless of the pet / name of the instance. aka grab the pets that are on a course from the DOM and pass that to the function in a loop.

**Comment by w35l3y** [comment]
You are thinking most likely as having a singleton. This is one of the problems with my old libs, they couldn't keep custom states.
It's very difficult to maintain custom states for each case when using singleton (single instance to everything)

**Comment by jacobkossman** [comment]
Fair enough. I don't have any problem making an instance for each pet just didn't realize that was the way to do it. Feel free to disregard those commits and i'll update my scripts accordingly. I'm about to push a inventory include as well, just fyi :)

**Pull request merged**
